# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171011_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='img900by650',
        ),
    ]
